# -*- coding: utf-8 -*-
"""fillna_hawks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zBzLspz6ItdVU4CS6bQsghiPxMk7eaju
"""

import pandas as pd
df = pd.read_csv('hawks.csv')

df.describe().loc[['mean']]

vaild_cols = ['Wing', 'Weight', 'Culmen', 'Hallux', 'Tail', 'StandardTail', 'Tarsus', 'WingPitFat', 'KeelFat', 'Crop']
def custom_fillna(col):
    if col.name in vaild_cols:
        col = col.fillna(round(col.mean(), 2))
        
    return col
res = df.apply(custom_fillna)

# move Class col to the end
res = res[ [ col for col in res.columns if col != 'Species' ] + ['Species'] ]

res.to_csv('hawks_fillna.csv', index=False)

res