giang_vien(le_Ngoc_Thanh).
truc_thuoc(thi_giac_may_tinh_va_dieu_khien_hoc_thong_minh,cNTT).
truong_bo_mon(X,thi_giac_may_tinh_va_dieu_khien_hoc_thong_minh).
truc_thuoc(X,vatly-vatlykythuat).
truong_khoa(le_Vu_Tuan_Hung,vatly-vatlykythuat).
truc_thuoc(toi_uu_va_He_thong,toan-tinhoc).
hoc_vi(X,tS).
hoc_vi(huynh_Huu_Thuan,thS).
phong(khoa_hoc_may_tinh,i81).
hoc_ham(X,pGS).
hoc_ham(X,gS).
khoa(X).
truc_thuoc(X,dia_chat).
nam(X).
nu(X).
truc_thuoc(X,cNTT).
pho_khoa(X,cNTT).
pho_khoa(X,hoa_hoc).
truc_thuoc(X,sinh_hoc-cong_nghe_sinh_hoc).
truc_thuoc(X,khoa_hoc_va_Cong_nghe_vat_lieu).